package com.zjx.opensource.codetemplate.mapper;

import com.zjx.opensource.codetemplate.model.CodeGenTest;
import com.zjx.opensource.codetemplate.model.CodeGenTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CodeGenTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_test
     *
     * @mbg.generated
     */
    long countByExample(CodeGenTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_test
     *
     * @mbg.generated
     */
    int deleteByExample(CodeGenTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_test
     *
     * @mbg.generated
     */
    int insert(CodeGenTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_test
     *
     * @mbg.generated
     */
    int insertSelective(CodeGenTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_test
     *
     * @mbg.generated
     */
    List<CodeGenTest> selectByExample(CodeGenTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_test
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CodeGenTest record, @Param("example") CodeGenTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_gen_test
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CodeGenTest record, @Param("example") CodeGenTestExample example);
}